#ifndef PLATFORM_CONTRACT_H
#define PLATFORM_CONTRACT_H

#include <stdint.h>

/* STM32F103CBT6 internal Flash: 128 KiB, 1 KiB erase pages.
 * （C8T6 64KB 同样兼容：分区地址不变，App 占满剩余空间） */
#define PLATFORM_FLASH_BASE          UINT32_C(0x08000000)
#define PLATFORM_FLASH_SIZE          UINT32_C(0x00020000)
#define PLATFORM_FLASH_END           (PLATFORM_FLASH_BASE + PLATFORM_FLASH_SIZE)
#define PLATFORM_FLASH_PAGE_SIZE     UINT32_C(0x00000400)

#define PLATFORM_BOOT_ADDR           UINT32_C(0x08000000)
#define PLATFORM_BOOT_SIZE           UINT32_C(0x00003000)   /* 12 KiB */
#define PLATFORM_FLAG_ADDR           UINT32_C(0x08003000)
#define PLATFORM_FLAG_SIZE           UINT32_C(0x00000400)
/* WiFi 参数已由 ESP01S / 外部 Flash 存储，内部不再划分 WiFi 分区，
 * App 分区直接从标志区之后开始。 */
#define PLATFORM_APP_ADDR            UINT32_C(0x08003400)
#define PLATFORM_APP_SIZE            UINT32_C(0x0001CC00)   /* 115 KiB，占满 128KB */

#define PLATFORM_BOOT_END            (PLATFORM_BOOT_ADDR + PLATFORM_BOOT_SIZE)
#define PLATFORM_FLAG_END            (PLATFORM_FLAG_ADDR + PLATFORM_FLAG_SIZE)
#define PLATFORM_APP_END             (PLATFORM_APP_ADDR + PLATFORM_APP_SIZE)

#define PLATFORM_SRAM_BASE           UINT32_C(0x20000000)
#define PLATFORM_SRAM_SIZE           UINT32_C(0x00005000)
#define PLATFORM_SRAM_END            (PLATFORM_SRAM_BASE + PLATFORM_SRAM_SIZE)

/* W25Q128 external Flash: 16 MiB, 4 KiB erase sectors. */
#define PLATFORM_EXT_FLASH_SIZE      UINT32_C(0x01000000)
#define PLATFORM_EXT_SECTOR_SIZE     UINT32_C(0x00001000)
#define PLATFORM_DATA_ADDR           UINT32_C(0x00000000)
#define PLATFORM_DATA_SIZE           UINT32_C(0x00C00000)
#define PLATFORM_FIRMWARE_ADDR       UINT32_C(0x00C00000)
#define PLATFORM_FIRMWARE_SIZE       UINT32_C(0x003F0000)
#define PLATFORM_METADATA_ADDR       UINT32_C(0x00FF0000)
#define PLATFORM_METADATA_SIZE       UINT32_C(0x00010000)
#define PLATFORM_METADATA_PRIMARY_ADDR PLATFORM_METADATA_ADDR
#define PLATFORM_METADATA_BACKUP_ADDR  (PLATFORM_METADATA_ADDR + PLATFORM_EXT_SECTOR_SIZE)
#define PLATFORM_FIRMWARE_MAX_SIZE     PLATFORM_APP_SIZE
#define PLATFORM_FIRMWARE_ERASE_SIZE   UINT32_C(0x0001D000)   /* ≥ APP_SIZE(0x1CC00)，4KB 扇区对齐 */

#define PLATFORM_DATA_END            (PLATFORM_DATA_ADDR + PLATFORM_DATA_SIZE)
#define PLATFORM_FIRMWARE_END        (PLATFORM_FIRMWARE_ADDR + PLATFORM_FIRMWARE_SIZE)
#define PLATFORM_METADATA_END        (PLATFORM_METADATA_ADDR + PLATFORM_METADATA_SIZE)

#define PLATFORM_CONCAT_INNER(a, b) a##b
#define PLATFORM_CONCAT(a, b) PLATFORM_CONCAT_INNER(a, b)
#define PLATFORM_STATIC_ASSERT(expr) \
    typedef char PLATFORM_CONCAT(platform_static_assert_, __LINE__)[(expr) ? 1 : -1]

PLATFORM_STATIC_ASSERT(PLATFORM_BOOT_END == PLATFORM_FLAG_ADDR);
PLATFORM_STATIC_ASSERT(PLATFORM_FLAG_END == PLATFORM_APP_ADDR);
PLATFORM_STATIC_ASSERT(PLATFORM_APP_END == PLATFORM_FLASH_END);
PLATFORM_STATIC_ASSERT((PLATFORM_BOOT_SIZE % PLATFORM_FLASH_PAGE_SIZE) == 0U);
PLATFORM_STATIC_ASSERT((PLATFORM_FLAG_SIZE % PLATFORM_FLASH_PAGE_SIZE) == 0U);
PLATFORM_STATIC_ASSERT((PLATFORM_APP_SIZE % PLATFORM_FLASH_PAGE_SIZE) == 0U);

PLATFORM_STATIC_ASSERT(PLATFORM_DATA_ADDR == 0U);
PLATFORM_STATIC_ASSERT(PLATFORM_DATA_END == PLATFORM_FIRMWARE_ADDR);
PLATFORM_STATIC_ASSERT(PLATFORM_FIRMWARE_END == PLATFORM_METADATA_ADDR);
PLATFORM_STATIC_ASSERT(PLATFORM_METADATA_END == PLATFORM_EXT_FLASH_SIZE);
PLATFORM_STATIC_ASSERT((PLATFORM_DATA_SIZE % PLATFORM_EXT_SECTOR_SIZE) == 0U);
PLATFORM_STATIC_ASSERT((PLATFORM_FIRMWARE_SIZE % PLATFORM_EXT_SECTOR_SIZE) == 0U);
PLATFORM_STATIC_ASSERT((PLATFORM_METADATA_SIZE % PLATFORM_EXT_SECTOR_SIZE) == 0U);
PLATFORM_STATIC_ASSERT(PLATFORM_METADATA_BACKUP_ADDR < PLATFORM_METADATA_END);
PLATFORM_STATIC_ASSERT(PLATFORM_FIRMWARE_ERASE_SIZE >= PLATFORM_FIRMWARE_MAX_SIZE);
PLATFORM_STATIC_ASSERT((PLATFORM_FIRMWARE_ERASE_SIZE % PLATFORM_EXT_SECTOR_SIZE) == 0U);

#endif /* PLATFORM_CONTRACT_H */
