# -*- coding: utf-8 -*-
"""
gen_music_fw.py — 从 tools/music/music_pack.mub 提取 5 首曲目数据，
生成 module/music_fw.c（多曲 MUB1 容器，供 EIDE Music target 编译出 Music.bin）。
输出 C 文件按 music.sct 的 4 段布局：
  HDR(36) + ENT(16*N) + NAME(64*N) + NOTES(多段)
"""
import os, re, struct

BASE = os.path.dirname(os.path.abspath(__file__))
MUB = os.path.join(BASE, 'music', 'music_pack.mub')
OUT_C = os.path.join(BASE, '..', 'module', 'music_fw.c')

d = open(MUB, 'rb').read()
magic, ver, n, flags, fsz, crc, name_off, name_sz, tbl_off, rsvd = struct.unpack('<IIHHIIIIII', d[:36])
assert magic == 0x3142554D

tracks = []
for i in range(n):
    no, ns, noff, nl, r2 = struct.unpack('<IIIHH', d[tbl_off + i * 16: tbl_off + i * 16 + 16])
    name = d[name_off + noff:name_off + noff + nl].decode('utf-8')
    notes = []
    for k in range(ns // 4):
        f, du = struct.unpack('<HH', d[no + k * 4:no + k * 4 + 4])
        notes.append((f, du))
    tracks.append((name, notes))
    print('%-22s notes=%d' % (name, len(notes)))

NAME_MAX = 64
ENT = 16 * n
NAME_OFF = 36 + ENT
NOTES_OFF = NAME_OFF + NAME_MAX * n
FILE_SIZE = NOTES_OFF + sum(len(t[1]) * 4 for t in tracks)


def b(v, k):
    return (v >> (8 * k)) & 0xFF


def fmt_notes(notes):
    out = []
    line = '    '
    for (f, du) in notes:
        s = '%d,%d,' % (f, du)
        if len(line) + len(s) > 96:
            out.append(line.rstrip())
            line = '    '
        line += s
    if line.strip():
        out.append(line.rstrip())
    return '\n'.join(out)


def utf8_bytes(name):
    return ['0x%02X' % c for c in name.encode('utf-8')]


# ---- 生成 music_fw.c ----
lines = []
lines.append('/*')
lines.append(' * music_fw.c - Music firmware source (EIDE target: Music)')
lines.append(' *')
lines.append(' * GENERATED by tools/gen_music_fw.py from tools/music/music_pack.mub')
lines.append(' * Build with EIDE Music target -> build/.../Music.bin, upload via')
lines.append(' * device "Music -> Upload" web page into external flash.')
lines.append(' * MUB1 container: HDR(36) + ENT(16*N) + NAME(64*N) + NOTES(multi)')
lines.append(' * NOTE: names are UTF-8 byte escapes (armcc parses GBK on zh systems).')
lines.append(' */')
lines.append('#include <stdint.h>')
lines.append('')
lines.append('#define HDR_SIZE    %d' % 36)
lines.append('#define ENT_OFF     %d' % 36)
lines.append('#define NAME_OFF    %d' % NAME_OFF)
lines.append('#define NOTES_OFF   %d' % NOTES_OFF)
lines.append('#define NAME_MAX    %d' % NAME_MAX)
lines.append('#define TRACKS      %d' % n)
lines.append('#define NOTE_BYTES  %d' % sum(len(t[1]) * 4 for t in tracks))
lines.append('#define FILE_SIZE   %d' % FILE_SIZE)
lines.append('')
lines.append('/* ---- name area: 64B fixed per track ---- */')
for i, (name, notes) in enumerate(tracks):
    nb = utf8_bytes(name)
    fill = 64 - len(nb)
    arr = nb + ['0x00'] * fill
    lines.append('__attribute__((section("MUS_NAME"), used))')
    lines.append('const unsigned char mus_name_%d[NAME_MAX] = { %s };' % (i, ', '.join(arr)))
lines.append('')
lines.append('/* ---- notes area: {u16 freq, u16 dur} pairs, 0,0 end marker ---- */')
for i, (name, notes) in enumerate(tracks):
    lines.append('__attribute__((section("MUS_NOTES"), used))')
    lines.append('const uint16_t mus_notes_%d[] = {' % i)
    lines.append(fmt_notes(notes + [(0, 0)]))
    lines.append('};')
lines.append('')
lines.append('#define B0(v) ((unsigned char)((uint32_t)(v) & 0xFFu))')
lines.append('#define B1(v) ((unsigned char)(((uint32_t)(v) >> 8) & 0xFFu))')
lines.append('#define B2(v) ((unsigned char)(((uint32_t)(v) >> 16) & 0xFFu))')
lines.append('#define B3(v) ((unsigned char)(((uint32_t)(v) >> 24) & 0xFFu))')
lines.append('')
lines.append('/* ---- 36B header ---- */')
lines.append('__attribute__((section("MUS_HDR"), used))')
lines.append('const unsigned char mus_hdr[HDR_SIZE] = {')
lines.append("    'M', 'U', 'B', '1',")
lines.append('    0x01, 0x00, 0x00, 0x00,')
lines.append('    TRACKS & 0xFF, (TRACKS >> 8) & 0xFF,')
lines.append('    0x00, 0x00,')
lines.append('    B0(FILE_SIZE), B1(FILE_SIZE), B2(FILE_SIZE), B3(FILE_SIZE),')
lines.append('    0x00, 0x00, 0x00, 0x00,')
lines.append('    B0(NAME_OFF), B1(NAME_OFF), B2(NAME_OFF), B3(NAME_OFF),')
lines.append('    B0(NAME_MAX * TRACKS), B1(NAME_MAX * TRACKS), B2(NAME_MAX * TRACKS), B3(NAME_MAX * TRACKS),')
lines.append('    B0(ENT_OFF), B1(ENT_OFF), B2(ENT_OFF), B3(ENT_OFF),')
lines.append('    0x00, 0x00, 0x00, 0x00,')
lines.append('};')
lines.append('')
lines.append('/* ---- 16B per-track entries ---- */')
lines.append('__attribute__((section("MUS_ENT"), used))')
lines.append('const unsigned char mus_ent[%d] = {' % (ENT))
off = NOTES_OFF
for i, (name, notes) in enumerate(tracks):
    nb = len(notes) * 4
    lines.append('    B0(%d), B1(%d), B2(%d), B3(%d),' % (off, off, off, off))
    lines.append('    B0(%d), B1(%d), B2(%d), B3(%d),' % (nb, nb, nb, nb))
    lines.append('    B0(%d), B1(%d), B2(%d), B3(%d),' % (i * 64, i * 64, i * 64, i * 64))
    lines.append('    B0(%d), B1(%d),' % (len(name.encode('utf-8')), len(name.encode('utf-8'))))
    lines.append('    0x00, 0x00,')
    off += nb
lines.append('};')

open(OUT_C, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print('generated:', OUT_C, 'FILE_SIZE=%d' % FILE_SIZE, 'NOTES_OFF=0x%X' % NOTES_OFF)